# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoGlyph
                                 A QGIS plugin
 Herramienta de segmentación y etiquetado de geoglifos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-11
        copyright            : (C) 2026 by Grupo 09 - Taller de Integración
        email                : javipaz.larrain@uc.cl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoGlyph class from file GeoGlyph.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoglyph import GeoGlyph

    return GeoGlyph(iface)
