# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoGlyph
                                 A QGIS plugin
 Herramienta de segmentación y etiquetado de geoglifos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Grupo 09 - Taller de Integración
        email                : javipaz.larrain@uc.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# -*- coding: utf-8 -*-
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *
from .geoglyph_dialog import GeoGlyphDialog
from .geoglyph_panel import GeoGlyphPanel
from .http_worker import EnhanceWorker  # ← nuevo en TIGS-42
import os.path


class GeoGlyph:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', 'GeoGlyph_{}.qm'.format(locale)
        )
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&GeoGlyph')
        self.panel = None
        self._worker = None  # referencia al worker activo (evita GC prematuro)

    def tr(self, message):
        return QCoreApplication.translate('GeoGlyph', message)

    def add_action(
        self, icon_path, text, callback, enabled_flag=True,
        add_to_menu=True, add_to_toolbar=True,
        status_tip=None, whats_this=None, parent=None
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToRasterMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Crea entradas de menú, toolbar y panel lateral."""
        icon_path = ':/plugins/geoglyph/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GeoGlyph'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )

        self.panel = GeoGlyphPanel(self.iface, self.iface.mainWindow())

        # Conexiones de botones
        self.panel.btn_abrir_tiff.clicked.connect(self.abrir_geotiff)
        self.panel.btn_inferencia.clicked.connect(self._ejecutar_inferencia)  # ← nuevo

        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.panel)

    def unload(self):
        """Elimina el plugin del menú y toolbar de QGIS."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(self.tr(u'&GeoGlyph'), action)
            self.iface.removeToolBarIcon(action)

        if self.panel is not None:
            self.iface.removeDockWidget(self.panel)
            self.panel = None

        # Detener worker si sigue corriendo al cerrar el plugin
        if self._worker is not None and self._worker.isRunning():
            self._worker.quit()
            self._worker.wait()

    def abrir_geotiff(self):
        """Abre el diálogo para cargar un GeoTIFF."""
        dlg = GeoGlyphDialog(self.iface)
        dlg.exec_()

    def run(self):
        """Muestra/oculta el panel lateral."""
        if self.panel is not None:
            self.panel.setVisible(not self.panel.isVisible())

    # ── TIGS-42: Comunicación HTTP asíncrona ──────────────────────────────────

    def _ejecutar_inferencia(self):
        """
        Lanza EnhanceWorker en un QThread para llamar POST /enhance
        sin bloquear el hilo principal de QGIS.
        """
        # Evitar doble-click mientras hay una llamada en curso
        if self._worker is not None and self._worker.isRunning():
            return

        self.panel.btn_inferencia.setEnabled(False)
        self.panel.lbl_status.setText("Estado: Conectando con backend...")
        self.panel.lbl_status.setStyleSheet(
            "color: orange; font-size: 10px; margin-left: 4px;"
        )

        # bbox placeholder — en iteraciones futuras vendrá del ROI seleccionado en QGIS
        self._worker = EnhanceWorker(bbox=[0, 0, 256, 256], band=1)
        self._worker.finished.connect(self._on_inferencia_ok)
        self._worker.error.connect(self._on_inferencia_error)
        self._worker.start()

    def _on_inferencia_ok(self, status_code, elapsed, body):
        """Callback ejecutado en el hilo principal cuando el worker termina bien."""
        proc_ms = body.get("processing_time_ms", "—")
        self.panel.lbl_status.setText(
            f"Estado: HTTP {status_code} · {elapsed:.2f}s · backend: {proc_ms}ms"
        )
        self.panel.lbl_status.setStyleSheet(
            "color: green; font-size: 10px; margin-left: 4px;"
        )
        self.panel.btn_inferencia.setEnabled(True)

    def _on_inferencia_error(self, msg):
        """Callback ejecutado en el hilo principal cuando el worker falla."""
        self.panel.lbl_status.setText(f"Error: {msg}")
        self.panel.lbl_status.setStyleSheet(
            "color: red; font-size: 10px; margin-left: 4px;"
        )
        self.panel.btn_inferencia.setEnabled(True)