# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoGlyphDialog
                                 A QGIS plugin
 Herramienta de segmentación y etiquetado de geoglifos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Grupo 09 - Taller de Integración
        email                : javipaz.larrain@uc.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


from qgis.core import QgsRasterLayer, QgsProject

# This loads your .ui file so that PyQt can populate your plugin with the
# elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geoglyph_dialog_base.ui'))


class GeoGlyphDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(GeoGlyphDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.iface = iface

        if self.layout() is None:
            from qgis.PyQt.QtWidgets import QVBoxLayout
            layout = QVBoxLayout()
            self.setLayout(layout)

        # Crear el botón "Abrir GeoTIFF"
        self.btn_open_tiff = QtWidgets.QPushButton("Abrir GeoTIFF", self)
        self.btn_open_tiff.clicked.connect(self.open_geotiff)

        # Agregar el botón al layout del diálogo
        self.layout().addWidget(self.btn_open_tiff)

    def open_geotiff(self):
        # Abre el explorador de archivos para seleccionar un .tif
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self,
            "Seleccionar GeoTIFF",
            "",
            "GeoTIFF (*.tif *.tiff)"
        )

        if not file_path:
            return  # El usuario canceló

        # Obtener el nombre del archivo sin extensión como nombre de la capa
        layer_name = os.path.splitext(os.path.basename(file_path))[0]

        # Crear la capa raster
        layer = QgsRasterLayer(file_path, layer_name)

        if not layer.isValid():
            QtWidgets.QMessageBox.critical(
                self,
                "Error",
                f"No se pudo cargar el archivo:\n{file_path}"
            )
            return

        # Agregar la capa al proyecto de QGIS
        QgsProject.instance().addMapLayer(layer)

        QtWidgets.QMessageBox.information(
            self,
            "Éxito",
            f"Capa '{layer_name}' cargada correctamente.\nCRS: {layer.crs().authid()}"
        )
