# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoGlyph
                                 A QGIS plugin
 Herramienta de segmentación y etiquetado de geoglifos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Grupo 09 - Taller de Integración
        email                : javipaz.larrain@uc.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .geoglyph_dialog import GeoGlyphDialog
from .geoglyph_panel import GeoGlyphPanel
import os.path


class GeoGlyph:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoGlyph_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoGlyph')
        self.panel = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        #self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoGlyph', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geoglyph/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GeoGlyph'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        #self.first_start = True

        # Crear y registrar el panel lateral
        self.panel = GeoGlyphPanel(self.iface, self.iface.mainWindow())

        # Conectar el botón "Abrir GeoTIFF" del panel al diálogo existente
        self.panel.btn_abrir_tiff.clicked.connect(self.abrir_geotiff)

        # Conectar el botón "Aplicar Color Ramp" del panel
        self.panel.btn_color_ramp.clicked.connect(self.apply_color_ramp)

        #Modificar número de bandas según capa seleccionada
        self.iface.layerTreeView().selectionModel().selectionChanged.connect(self.cargar_bandas)

        # Agregar el panel a QGIS (lado derecho por defecto)
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.panel)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&GeoGlyph'),
                action)
            self.iface.removeToolBarIcon(action)
        
        if self.panel is not None:
            self.iface.removeDockWidget(self.panel)
            self.panel = None

    def abrir_geotiff(self):
        """Abre el diálogo para cargar un GeoTIFF."""
        dlg = GeoGlyphDialog(self.iface)
        dlg.exec_()

    def cargar_bandas(self): #Número de bandas que tiene una capa
        layers = self.iface.layerTreeView().selectedLayers() #capa seleccionada

        if not layers:
            return

        layer = layers[0]
        provider = layer.dataProvider()

        #Obtener número de bandas
        band_count = provider.bandCount()

        #Modificar botón lateral
        self.panel.combo_band.clear()

        for i in range(1, band_count + 1):
            self.panel.combo_band.addItem(str(i))

    def apply_color_ramp(self):
        from qgis.core import(
            QgsRasterShader, #aplica los colores
            QgsColorRampShader, #define los colores
            QgsSingleBandPseudoColorRenderer, #muestra los resultados
            QgsProject, #agrega la capa al mapa
        )
        from PyQt5.QtGui import QColor #define colores

        #Obtener tipo de esquema de color
        ramp_type = self.panel.combo_color_ramp.currentText()
        
        #Obtener la capa seleccionada en QGIS
        layer = self.iface.activeLayer()

        #Evita error si el usuario no seleccionó nada
        if layer is None:
            self.iface.messageBar().pushMessage("Error", "No hay capa activa", level=2)
            return

        #Acceder a los datos del ráster
        provider = layer.dataProvider()

        #Banda seleccionada por usuario
        band = int(self.panel.combo_band.currentText())

        # Obtener min/max automáticamente
        stats = provider.bandStatistics(band)
        min_val = stats.minimumValue
        max_val = stats.maximumValue

        # Crear color ramp (viridis simple, rojo, verde, azul)
        color_ramp = QgsColorRampShader()
        color_ramp.setColorRampType(QgsColorRampShader.Interpolated)

        #Definir cómo mapear los valores (colores) según esquema escogido por usuario
        #viridis (paleta secuencial, de oscuro a claro)
        if ramp_type == "viridis":
            items = [
                QgsColorRampShader.ColorRampItem(min_val, QColor(68, 1, 84)), #valores bajos oscuros (morado oscuro)
                QgsColorRampShader.ColorRampItem((min_val + max_val) / 2, QColor(32, 144, 140)), #valores medios un poco más claros (verde/azul)
                QgsColorRampShader.ColorRampItem(max_val, QColor(253, 231, 37)), #valores altos claros (amarillo)
            ]
        #RdYlGn (esquema divergente tipo semáforo (rojo-> amarillo -> verde))
        elif ramp_type == "RdYlGn":
            items = [
                QgsColorRampShader.ColorRampItem(min_val, QColor(165, 0, 38)), #valores bajos o críticos rojo
                QgsColorRampShader.ColorRampItem((min_val + max_val) / 2, QColor(255, 255, 191)), #valores medios amarillo
                QgsColorRampShader.ColorRampItem(max_val, QColor(0, 104, 55)), #valores altos o favorables verde
            ]

        color_ramp.setColorRampItemList(items)

        #Aplicar la lógica del color ramp
        shader = QgsRasterShader()
        shader.setRasterShaderFunction(color_ramp)

        #Mostrar la banda seleccionada con estos colores
        renderer = QgsSingleBandPseudoColorRenderer(provider, band, shader)

        # Crear nueva capa para no modificar original
        new_layer = layer.clone()
        new_layer.setRenderer(renderer)
        new_layer.setName(f"{layer.name()}_{ramp_type}")

        #Mostrar en QGIS, en el panel de capas
        QgsProject.instance().addMapLayer(new_layer)



    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        #self.dlg = GeoGlyphDialog(self.iface)

        # show the dialog
        #self.dlg.show()
        # Run the dialog event loop
        #result = self.dlg.exec_()
        # See if OK was pressed
        #if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
        #    pass

        """Muestra/oculta el panel lateral."""
        if self.panel is not None:
            self.panel.setVisible(not self.panel.isVisible())
